server:
  port: 8080
spring:
  webflux:
    base-path: ${BASE_PATH:/api/v1/api}
  application:
    name: aplicacion

adapter:
  rest-consumer:
    timeout: 5000
    base-url: http://localhost:3013
    uri:
      get-books: /products

routes:
  path-mapping:
    api:
      products-route: /products