server:
  port: 8080
spring:
  webflux:
    base-path: /api/v1/api
  application:
    name: aplicacion

adapter:
  rest-consumer:
    timeout: 5000
    base-url: https://api.escuelajs.co/api/v1
    uri:
      get-books: /products

routes:
  path-mapping:
    api:
      products-route: /products